### ISSUE TITLE
Class 'AuthProvider\\Token' not found

### ISSUE THREAD

**Issue by oktaykalfa** [edamov/pushok#132]
Hello Developer,

 // Be aware of thing that Token will stale after one hour, so you should generate it again.
// Can be useful when trying to send pushes during long-running tasks
$authProvider = \AuthProvider\Token::create($options);

this line is not working even if i added **"use Pushok\AuthProvider;"**

I see no replacement. What can i do for this? Thanks for your helps.

Best Regards.

**Comment by stollr** [comment]
If you have installed the library with composer, did you include composer's autoload file?

Like this:
```php
include 'vendor/autoload.php';
```

If you have added `use Pushok\AuthProvider;` to your PHP file, then you have to instantiate the token like this:
```php
$authProvider = AuthProvider\Token::create($options); // bo backslash in front of AuthProvider
```

Otherwise PHP will search for the AuthProvider in the global namespace instead of the Pushok namespace.

**Comment by bardia-far** [comment]
Hi
I still have this problem

**Comment by yasinahmed81** [comment]
I had this issue on my AWS instance, please install the extensions, `gmp` and `bcmath`, then restart your server.
